//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornamentals_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoImagen
    {
        public int ProductoImagenId { get; set; }
        public int ProductoId { get; set; }
        public string Imagen { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
